n = input("Digite algo: ")
print("É alphabeto?", n.isalpha())
print("É alphanumérico?", n.isalnum())
print("É decimal?", n.isdecimal())
print("Está em minúscilas?", n.islower())
print("Está em maiúsculas?", n.isupper())
print("É espaço?", n.isspace())
print("É possível imprimir?", n.isprintable())
print("É numérioc?", n.isnumeric())
print("É um identificador?", n.isidentifier())
print(type(n))
